version: "2"

services:
    influxdb:
        container_name: monitoring_influxdb
        image: influxdb:1.3.7-alpine
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - "./data/influxdb:/var/lib/influxdb"
            - "./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh"
        env_file: .env

    grafana:
        container_name: monitoring_grafana
        image: grafana/grafana:4.6.0
        restart: unless-stopped
        depends_on:
            - influxdb
        ports:
            - "3000:3000"
        volumes:
            - "./data/grafana:/var/lib/grafana"
        env_file: .env

    telegraf:
        container_name: monitoring_telegraf
        image: telegraf:1.4.3-alpine
        restart: unless-stopped
        environment:
            HOST_PROC: /rootfs/proc
            HOST_SYS: /rootfs/sys
            HOST_ETC: /rootfs/etc
        env_file: .env
        depends_on:
            - influxdb
        ports:
            - "8125:8125/udp"
        volumes:
            - "./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/var/run/utmp:/var/run/utmp:ro"
            - "/sys:/rootfs/sys:ro"
            - "/proc:/rootfs/proc:ro"
            - "/etc:/rootfs/etc:ro"
