version: "2"

services:
    influxdb:
        container_name: influxdb
        image: influxdb:1.3.7-alpine
        restart: unless-stopped
        networks:
            - main
        ports:
            - "8086:8086"
            - "8083:8083"
        volumes:
            - "./data/influxdb:/var/lib/influxdb"
        env_file: .env

    grafana:
        container_name: grafana
        image: grafana/grafana:4.6.0
        restart: unless-stopped
        networks:
            - main
        depends_on:
            - influxdb
        ports:
            - "3000:3000"
        volumes:
            - "./data/grafana:/var/lib/grafana"
        env_file: .env

    telegraf:
        container_name: telegraf
        image: telegraf:1.4.3-alpine
        restart: unless-stopped
        networks:
            - main
        environment:
            HOST_PROC: /rootfs/proc
            HOST_SYS: /rootfs/sys
            HOST_ETC: /rootfs/etc
        env_file: .env
        depends_on:
            - influxdb
        ports:
            - "8125:8125/udp"
        volumes:
            - "./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/var/run/utmp:/var/run/utmp:ro"
            - "/sys:/rootfs/sys:ro"
            - "/proc:/rootfs/proc:ro"
            - "/etc:/rootfs/etc:ro"

networks:
    main:
        driver: bridge
        ipam:
            config:
            -   subnet: 172.22.0.0/16
                gateway: 172.22.0.1
